### ISSUE TITLE
J interpreter: meaning of `t`

### ISSUE THREAD

**Issue by doug-moen** [bollu/bollu.github.io#12]
> What is the t variable really tracking?

Each value is either an array of numbers (t==0) or it is an array of boxes (t==1).
So `t` is the type of the scalars that make up the array.

The monadic box operator `<` converts a value into a box.

IMO, since I still don't understand all of the code.

**Comment by bollu** [comment]
Thank you. Do you know what it could be standing for? I guessed "type", but I could be wrong

**Comment by doug-moen** [comment]
I believe that `t` is type, `r` is rank, `d` is dimensions. I don't know what `p` stands for.

**Comment by bollu** [comment]
P is pointer I feel, as in, a pointer to data.

sent from my phone, please excuse any typos!
