### ISSUE TITLE
J interpreter: create a multidimensional array

### ISSUE THREAD

**Issue by doug-moen** [bollu/bollu.github.io#13]
My theory is that
```
2 2#~4
```
should produce a 2x2 matrix. It is only a theory, since I am so far unable to run the interpreter without it crashing. It seems to me that `#` is the APL "rho" operator and `~` is the APL "iota" operator.

**Comment by doug-moen** [comment]
"sha" means "shape". It is the monadic case of the `#` operator. It returns the shape of an array (a list of the array dimensions).

"rsh" means "reshape". It is the dyadic case of the `#` operator. The left argument is the dimensions of the new array that you wish to construct. The right argument is a list of scalars that are used to populate the positions of the new array that you create. The right argument is "reshaped" to have the dimensions given by the left argument.

**Comment by 0b01** [comment]
I think it's correct. I spent some time and fully understood what each line does: https://rickyhan.com/jekyll/update/2020/01/16/j-incunabulum-disected.html
