### ISSUE TITLE
How does one work with arrays in a linear language?

### ISSUE THREAD

**Issue by doug-moen** [bollu/bollu.github.io#14]
> Given an array of qubits xs: Qubit[], I want to switch to little endian. Due to no-cloning, I can't copy them! I suppose I can use recursion to build up a new "list". But this is not the efficient array version we know and love and want.
>
> The code that I want to work but does not:
> ```
> function switchEndian(xs: Qubit[]): Unit {
>     for(i in 0..Length(xs) - 1) {
>         Qubit q = xs[i]; // boom, this does not work!
>         xs[i] = xs[Length(xs) - 1 - i]
>         xs[Length(xs) - 1 - i] = q;
>     }
> }
> ```

You just need a linear swap function.
```
function switchEndian(xs: Qubit[]): Unit {
    for(i in 0..Length(xs) - 1) {
        swap(xs[i], xs[Length(xs) - 1 - i]);
    }
}
```

**Comment by bollu** [comment]
Right! My understanding is that Q# does not provide one, and hence it's un-implementable with the primtives they provide, correct?

**Comment by doug-moen** [comment]
I don't know Q#, but I believe that `swap` normally needs to be implemented as a primitive in a linear language. Unless there is maybe an alternative set of linear primitives from which you can implement `swap`. Does such an alternate set of primitives exist in the quantum realm?

My knowledge of quantum mechanics is limited. Quantum state can't be destroyed or cloned. There is a `teleport` operator that copies the state from A to B then leaves the state of A undefined. This requires A and B to be first entangled. Could you teleport A to C and B to D, then teleport C to B and D to A? If that is possible, then you have swapped A and B. There is an operation called "entanglement swapping" which works on 4 particles. It's not the swap operation we want, but maybe it could be used as part of the solution. There is a paper titled "General quantum-state swap: An XY-model analysis" which appears to claim that state swapping is possible (https://ui.adsabs.harvard.edu/abs/2012PhRvA..85d2328L/abstract). That's all I have right now. I don't understand quantum math so I'm not in a position to perform a complete analysis.
