### ISSUE TITLE
Resume link broken on the main website

### ISSUE THREAD

**Issue by ice1000** [bollu/bollu.github.io#37]
![image](https://user-images.githubusercontent.com/16398479/230982618-a0ce4479-fd6e-4e51-96da-729a664dafae.png)

This link is 404
![image](https://user-images.githubusercontent.com/16398479/230982735-a56a061f-e80f-477e-80d5-303454215cd4.png)

**Comment by bollu** [comment]
This is now fixed :)

**Comment by ice1000** [comment]
🤯🤯
