### ISSUE TITLE
Website security errors

### ISSUE THREAD

**Issue by seanfcarroll** [bollu/bollu.github.io#5]
Hi there,

Followed a Hacker News link to your repo, but I noticed there are security errors on your blog page. Thought you would want to know.

<img width="1066" alt="Screenshot 2019-06-04 at 06 41 17" src="https://user-images.githubusercontent.com/11340230/58851652-e6159780-8693-11e9-99f2-de52e397b7b0.png">

**Comment by bollu** [comment]
Hello. I've migrated away from hosting my own thing, so closing this
